// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Winner,
  Coord,
  DroppedPiece,
} from "./types";


export default __t.row({
  roomId: __t.u32().primaryKey().name("room_id"),
  get winner() {
    return __t.option(Winner);
  },
  get table() {
    return __t.array(__t.array(__t.option(DroppedPiece)));
  },
  get latestMove() {
    return __t.option(Coord).name("latest_move");
  },
});
