// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
	AlgebraicType,
	AlgebraicValue,
	BinaryReader,
	BinaryWriter,
	ConnectionId,
	DbConnectionBuilder,
	DbConnectionImpl,
	Identity,
	ProductType,
	ProductTypeElement,
	SubscriptionBuilderImpl,
	SumType,
	SumTypeVariant,
	TableCache,
	TimeDuration,
	Timestamp,
	deepEqual,
	type CallReducerFlags,
	type DbContext,
	type ErrorContextInterface,
	type Event,
	type EventContextInterface,
	type ReducerEventContextInterface,
	type SubscriptionEventContextInterface
} from '@clockworklabs/spacetimedb-sdk';
import { RoomPassword } from './room_password_type';
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from '.';

/**
 * Table handle for the table `room_password`.
 *
 * Obtain a handle from the [`roomPassword`] property on [`RemoteTables`],
 * like `ctx.db.roomPassword`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.roomPassword.on_insert(...)`.
 */
export class RoomPasswordTableHandle {
	tableCache: TableCache<RoomPassword>;

	constructor(tableCache: TableCache<RoomPassword>) {
		this.tableCache = tableCache;
	}

	count(): number {
		return this.tableCache.count();
	}

	iter(): Iterable<RoomPassword> {
		return this.tableCache.iter();
	}
	/**
	 * Access to the `roomId` unique index on the table `room_password`,
	 * which allows point queries on the field of the same name
	 * via the [`RoomPasswordRoomIdUnique.find`] method.
	 *
	 * Users are encouraged not to explicitly reference this type,
	 * but to directly chain method calls,
	 * like `ctx.db.roomPassword.roomId().find(...)`.
	 *
	 * Get a handle on the `roomId` unique index on the table `room_password`.
	 */
	roomId = {
		// Find the subscribed row whose `roomId` column value is equal to `col_val`,
		// if such a row is present in the client cache.
		find: (col_val: number): RoomPassword | undefined => {
			for (let row of this.tableCache.iter()) {
				if (deepEqual(row.roomId, col_val)) {
					return row;
				}
			}
		}
	};

	onInsert = (cb: (ctx: EventContext, row: RoomPassword) => void) => {
		return this.tableCache.onInsert(cb);
	};

	removeOnInsert = (cb: (ctx: EventContext, row: RoomPassword) => void) => {
		return this.tableCache.removeOnInsert(cb);
	};

	onDelete = (cb: (ctx: EventContext, row: RoomPassword) => void) => {
		return this.tableCache.onDelete(cb);
	};

	removeOnDelete = (cb: (ctx: EventContext, row: RoomPassword) => void) => {
		return this.tableCache.removeOnDelete(cb);
	};

	// Updates are only defined for tables with primary keys.
	onUpdate = (cb: (ctx: EventContext, oldRow: RoomPassword, newRow: RoomPassword) => void) => {
		return this.tableCache.onUpdate(cb);
	};

	removeOnUpdate = (cb: (ctx: EventContext, onRow: RoomPassword, newRow: RoomPassword) => void) => {
		return this.tableCache.removeOnUpdate(cb);
	};
}
