// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AutoDeleteGameHistoryTimer = __t.object("AutoDeleteGameHistoryTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type AutoDeleteGameHistoryTimer = __Infer<typeof AutoDeleteGameHistoryTimer>;

export const AutoDeleteRoomTimer = __t.object("AutoDeleteRoomTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type AutoDeleteRoomTimer = __Infer<typeof AutoDeleteRoomTimer>;

export const Coord = __t.object("Coord", {
  x: __t.u32(),
  y: __t.u32(),
});
export type Coord = __Infer<typeof Coord>;

export const DroppedPiece = __t.object("DroppedPiece", {
  teamId: __t.u32(),
  dropper: __t.identity(),
});
export type DroppedPiece = __Infer<typeof DroppedPiece>;

export const Game = __t.object("Game", {
  roomId: __t.u32(),
  get winner() {
    return __t.option(Winner);
  },
  get table() {
    return __t.array(__t.array(__t.option(DroppedPiece)));
  },
  get latestMove() {
    return __t.option(Coord);
  },
});
export type Game = __Infer<typeof Game>;

export const GameCurrentTeam = __t.object("GameCurrentTeam", {
  gameId: __t.u32(),
  teamId: __t.u32(),
});
export type GameCurrentTeam = __Infer<typeof GameCurrentTeam>;

export const GameHistory = __t.object("GameHistory", {
  id: __t.u32(),
  player: __t.identity(),
  won: __t.bool(),
  timestamp: __t.timestamp(),
});
export type GameHistory = __Infer<typeof GameHistory>;

export const HasDroppedPieceToGame = __t.object("HasDroppedPieceToGame", {
  id: __t.u32(),
  gameId: __t.u32(),
  joiner: __t.identity(),
  teamId: __t.u32(),
});
export type HasDroppedPieceToGame = __Infer<typeof HasDroppedPieceToGame>;

export const JoinRoom = __t.object("JoinRoom", {
  roomId: __t.u32(),
  joiner: __t.identity(),
  joinedAt: __t.timestamp(),
});
export type JoinRoom = __Infer<typeof JoinRoom>;

export const JoinTeam = __t.object("JoinTeam", {
  roomId: __t.u32(),
  joiner: __t.identity(),
  teamId: __t.u32(),
});
export type JoinTeam = __Infer<typeof JoinTeam>;

export const Message = __t.object("Message", {
  roomId: __t.u32(),
  sender: __t.identity(),
  sentAt: __t.timestamp(),
  text: __t.string(),
});
export type Message = __Infer<typeof Message>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  online: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const Room = __t.object("Room", {
  id: __t.u32(),
  title: __t.string(),
  owner: __t.identity(),
  createdAt: __t.timestamp(),
  hasPassword: __t.bool(),
});
export type Room = __Infer<typeof Room>;

export const RoomPassword = __t.object("RoomPassword", {
  roomId: __t.u32(),
  password: __t.string(),
});
export type RoomPassword = __Infer<typeof RoomPassword>;

export const StatsOneMonth = __t.object("StatsOneMonth", {
  player: __t.identity(),
  wins: __t.u32(),
  total: __t.u32(),
});
export type StatsOneMonth = __Infer<typeof StatsOneMonth>;

export const Team = __t.object("Team", {
  id: __t.u32(),
  gameId: __t.u32(),
  name: __t.string(),
});
export type Team = __Infer<typeof Team>;

export const Winner = __t.object("Winner", {
  teamId: __t.u32(),
  get coordinates() {
    return __t.array(Coord);
  },
});
export type Winner = __Infer<typeof Winner>;

