// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateGameReducer from "../create_game_reducer";
import CreateRoomReducer from "../create_room_reducer";
import DropPieceReducer from "../drop_piece_reducer";
import HelloReducer from "../hello_reducer";
import HelloWithTextReducer from "../hello_with_text_reducer";
import JoinToRoomReducer from "../join_to_room_reducer";
import JoinToTeamReducer from "../join_to_team_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import LeaveTeamReducer from "../leave_team_reducer";
import RestartGameHasWinnerReducer from "../restart_game_has_winner_reducer";
import RestartGameTableFullReducer from "../restart_game_table_full_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetNameReducer from "../set_name_reducer";

export type CreateGameParams = __Infer<typeof CreateGameReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type DropPieceParams = __Infer<typeof DropPieceReducer>;
export type HelloParams = __Infer<typeof HelloReducer>;
export type HelloWithTextParams = __Infer<typeof HelloWithTextReducer>;
export type JoinToRoomParams = __Infer<typeof JoinToRoomReducer>;
export type JoinToTeamParams = __Infer<typeof JoinToTeamReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type LeaveTeamParams = __Infer<typeof LeaveTeamReducer>;
export type RestartGameHasWinnerParams = __Infer<typeof RestartGameHasWinnerReducer>;
export type RestartGameTableFullParams = __Infer<typeof RestartGameTableFullReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;

